### ISSUE TITLE
Automatic selection of structure elements in mobile view

### ISSUE THREAD

**Issue by andre-hohmann** [slub/slub_digitalcollections#10] opened 2020-11-11 06:37 UTC
### Problem
In the mobile view (not in the small browser windows) the first structure element or the latest selection in the list of structure elements is automatically activated as soon as the structure tree is opened.
Only quick users can choose another structure element from the list.  
The behaviour is observed in "Digitale Sammlungen" und "Börsenblatt-Digital" (slub_digitalcollections). 

See also: #9 

### Solution
The structure elements in the list of structure elements should only be activated by a direct user interaction. 

### Examples
- http://digital.slub-dresden.de/id365171654
- http://digital.slub-dresden.de/id416501729

![strukturbaum](https://user-images.githubusercontent.com/14835770/98777136-80811b00-23f0-11eb-8464-1540cd59fd95.jpg)

**Comment by albig** [comment] 2020-11-11 08:42
@gnuj please have a look at it. Related maybe to #9.

**Comment by albig** [comment] 2020-11-13 16:00
Fixed by #11

**Closed by albig** 2020-11-13 16:00 UTC
Labels: bug

**Comment by andre-hohmann** [comment] 2020-11-14 07:45
Unfortunately, it does not seem to be fixed completely. 

It is not possible to find and describe a pattern. It is the best to navigate in http://digital.slub-dresden.de/id416501729 between the issues and within the issues in the articles and then back to a specific issue. 
Quite often, a structure element is activated automatically and makes it difficult to scroll the issues in the list of structure elements.

**Comment by gnuj** [comment] 2020-11-15 21:24
Thats a bit strange. I've tested it locally with some iphones and a ipad. It all worked as intended after the fixes. The same devices show the described error when calling the productive environment. Nevertheless i'll try to fix it again as soon i can reproduce the error locally. I'll keep you posted. Sorry for the inconvenience.
